apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api
spec:
  replicas: 5
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: test-api
  template:
    metadata:
      labels:
        app: test-api
    spec:
      containers:
        - image: pashacodefresh/argocd-test-image:1.11.2
          name: test-api
          ports:
            - containerPort: 1700
          readinessProbe:
            exec:
              command:
                - sleep
                - "300"
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
